### ISSUE TITLE
About code release.

### ISSUE THREAD

**Issue by zyrant** [Haiyang-W/CAGroup3D#1]
Dear sir

thank you for your excellent work.
I am curious about when will you release the code. thank.

best wishes

**Comment by pigtigger** [comment]
Thanks for your attention to our work. The code will be released in the next week.

**Comment by sohaibrabbani** [comment]
Congrats on the great work. When will the code be released? Thanks.

**Comment by pigtigger** [comment]
Hi sohaibrabbani, the code release is at the final stage and will take another 1-2 days due to the time loss of the CVPR rebuttal.
