### ISSUE TITLE
Input dimension requires for CAGroup3D

### ISSUE THREAD

**Issue by binbin-xu** [Haiyang-W/CAGroup3D#10]
Hi Haiyang,

Thank you very much for sharing your code.
The diagram figure in your repo shows that your method only requires colorless lidar points as input as the input dimension of NX3 shows. 
However, the detector in your method seems still requires color lidar in the dimension of NX6 to perform point feature initialisation? https://github.com/Haiyang-W/CAGroup3D/blob/d204233f4b6bdbeed0de5146f3acb78371da8c56/pcdet/models/detectors/cagroup3d.py#L18-L26 in the voxelization part.

Thank you very much for your help!

**Comment by Haiyang-W** [comment]
> Hi Haiyang,
> 
> Thank you very much for sharing your code. The diagram figure in your repo shows that your method only requires colorless lidar points as input as the input dimension of NX3 shows. However, the detector in your method seems still requires color lidar in the dimension of NX6 to perform point feature initialisation?
> 
> https://github.com/Haiyang-W/CAGroup3D/blob/d204233f4b6bdbeed0de5146f3acb78371da8c56/pcdet/models/detectors/cagroup3d.py#L18-L26
> 
> in the voxelization part.
> Thank you very much for your help!

Yeah, we follow the same pre-processing as FACF3D. It brings about 0.3~0.5 performance improvement in terms of map@0.25.  It's a common trick used in SoftGroup, PointGroup, FACF3D, and so on. Actually, the point cloud has a color, just to make it easier to draw and look good, we manually lightened the color. 

Hope that can ease your concern.

Best regards,
Haiyang
