### ISSUE TITLE
Reproduce the results on SUN-RGBD 

### ISSUE THREAD

**Issue by abc-def-g** [Haiyang-W/CAGroup3D#12]
Dear authors, 

I strictly follow the instructions to train the network on SUN-RGBD. The reproduced results are much lower than the reported results in the paper. And I also noticed a similar (closed) issue (#6). Could you please give me some advice to reproduce your results?

![image](https://user-images.githubusercontent.com/32691813/225171822-9fcbde8f-9445-40a1-9b31-fdddf7eed20e.png)
[log_train_20230314-171539.txt](https://github.com/Haiyang-W/CAGroup3D/files/10974901/log_train_20230314-171539.txt)

**Comment by Haiyang-W** [comment]
Did you use the data we provided?  Or maybe it's the problem of environment. Can you show me your environment? (conda list)

**Comment by Haiyang-W** [comment]
Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.

**Comment by abc-def-g** [comment]
> Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.

According to the readme (https://github.com/Haiyang-W/CAGroup3D#data-preparation), I generate the dataset following mmdetection. 
If I have to use your released data, not the dataset generated following the instructions,  to reproduce the results, please kindly inform me how to generate your data if possible.

**Comment by abc-def-g** [comment]
> Did you use the data we provided? Or maybe it's the problem of environment. Can you show me your environment? (conda list)

[conda-list.txt](https://github.com/Haiyang-W/CAGroup3D/files/10975715/conda-list.txt)

**Comment by Haiyang-W** [comment]
> > Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.
> 
> According to the readme (https://github.com/Haiyang-W/CAGroup3D#data-preparation), I generate the dataset following mmdetection. If I have to use your released data, not the dataset generated following the instructions, to reproduce the results, please kindly inform me how to generate your data if possible.

We have provided the pre-processed data in [here](https://drive.google.com/drive/folders/1sKvq4WBSEb4CWMdCTN6lCHLXnn3NwUv_). But It is the 50000 points sampled version.  See the [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). We are now updating this data in several hours (about 4 hours to upload our new data). You just copy this data to ./data .  Please see Readme for more details.

**Comment by Haiyang-W** [comment]
> > > Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.
> > 
> > 
> > According to the readme (https://github.com/Haiyang-W/CAGroup3D#data-preparation), I generate the dataset following mmdetection. If I have to use your released data, not the dataset generated following the instructions, to reproduce the results, please kindly inform me how to generate your data if possible.
> 
> We have provided the pre-processed data in [here](https://drive.google.com/drive/folders/1sKvq4WBSEb4CWMdCTN6lCHLXnn3NwUv_). But It is the 50000 points sampled version. See the [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). We are now updating this data in several hours (about 4 hours to upload our new data). You just copy this data to ./data . Please see Readme for more details.

Original SUN RGBD has been deleted. New version will be updated in few hours, pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). MMDet3D 1.0 has changed a lot in coordinate system. Pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/5#issuecomment-1437928925) for more details. You can generate data by MMDet3D 0.15.

**Comment by Haiyang-W** [comment]
> > > > Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.
> > > 
> > > 
> > > According to the readme (https://github.com/Haiyang-W/CAGroup3D#data-preparation), I generate the dataset following mmdetection. If I have to use your released data, not the dataset generated following the instructions, to reproduce the results, please kindly inform me how to generate your data if possible.
> > 
> > 
> > We have provided the pre-processed data in [here](https://drive.google.com/drive/folders/1sKvq4WBSEb4CWMdCTN6lCHLXnn3NwUv_). But It is the 50000 points sampled version. See the [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). We are now updating this data in several hours (about 4 hours to upload our new data). You just copy this data to ./data . Please see Readme for more details.
> 
> Original SUN RGBD has been deleted. New version will be updated in few hours, pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). MMDet3D 1.0 has changed a lot in coordinate system. Pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/5#issuecomment-1437928925) for more details. You can generate data by MMDet3D 0.15.

There was a problem uploading the files. They'll be uploaded by tonight.

**Comment by Haiyang-W** [comment]
> > > > > Please use our pre-processed data. MMDet3D 1.0 has a huge change, including the coordinate system.
> > > > 
> > > > 
> > > > According to the readme (https://github.com/Haiyang-W/CAGroup3D#data-preparation), I generate the dataset following mmdetection. If I have to use your released data, not the dataset generated following the instructions, to reproduce the results, please kindly inform me how to generate your data if possible.
> > > 
> > > 
> > > We have provided the pre-processed data in [here](https://drive.google.com/drive/folders/1sKvq4WBSEb4CWMdCTN6lCHLXnn3NwUv_). But It is the 50000 points sampled version. See the [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). We are now updating this data in several hours (about 4 hours to upload our new data). You just copy this data to ./data . Please see Readme for more details.
> > 
> > 
> > Original SUN RGBD has been deleted. New version will be updated in few hours, pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/11#issue-1620837968). MMDet3D 1.0 has changed a lot in coordinate system. Pls see [issue](https://github.com/Haiyang-W/CAGroup3D/issues/5#issuecomment-1437928925) for more details. You can generate data by MMDet3D 0.15.
> 
> There was a problem uploading the files. They'll be uploaded by tonight.

Sorry for the late update. The SUN RGBD data is uploaded [here](https://drive.google.com/drive/folders/1sKvq4WBSEb4CWMdCTN6lCHLXnn3NwUv_).  You can get the SOTA performance easily by this data (without sampling points). The training log and model weight will be uploaded in one day.

**Comment by abc-def-g** [comment]
How did you generate the datasets? Could you release your code for generating the datasets?  I have difficulties downloading huge datasets from google drive.  Or is it possible to upload your datasets to other cloud drives so that people from mainland China can easily access the datasets?

**Comment by Haiyang-W** [comment]
We use MMDet3d (0.15) to generate the SUN RGBD dataset, not 1.0 in your log. And turn off  the point sampling in SUN RGBD generation process (it will sample 50000 points originally, but we remove it.). That will boost the performance of +0.5. I suggest you use the data we generated, which might be easier for reproducing our performance. Thanks for your suggestions, I will consider upload it in Baidu cloud drive later.

**Comment by Haiyang-W** [comment]
> How did you generate the datasets? Could you release your code for generating the datasets? I have difficulties downloading huge datasets from google drive. Or is it possible to upload your datasets to other cloud drives so that people from mainland China can easily access the datasets?

[BaiduDrive](https://pan.baidu.com/s/1SO1YhvC9BZh5eFXYjt-a3g?pwd=8mfk#list/path=%2F) is provided. Hope that can ease your concern. With these data, you can achieve the SOTA performance easily.

Best regards.
Haiyang

**Comment by Haiyang-W** [comment]
> How did you generate the datasets? Could you release your code for generating the datasets? I have difficulties downloading huge datasets from google drive. Or is it possible to upload your datasets to other cloud drives so that people from mainland China can easily access the datasets?

Hi, have you solved your problem? Please feel free to contact me if you have any questions.

**Comment by abc-def-g** [comment]
With the new data, the results are closer to the reported results.
The reported average mAP@0.25 is 66.8(66.4),  the mAP@0.5 is 50.2(49.5).  However, the reproduced mAP@0.25 is 65.9, and mAP@0.5 is 47.4. All results are lower than the reported numbers in the paper. Especially the mAP@0.5 is still lower than the reported mAP@0.5 by **2.1**. Do you have any advice on my experiment?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/32691813/227530100-b66a33cf-e7c0-4c9e-921c-7118dcaeb45f.png">

**Comment by Haiyang-W** [comment]
> With the new data, the results are closer to the reported results. The reported average mAP@0.25 is 66.8(66.4), the mAP@0.5 is 50.2(49.5). However, the reproduced mAP@0.25 is 65.9, and mAP@0.5 is 47.4. All results are lower than the reported numbers in the paper. Especially the mAP@0.5 is still lower than the reported mAP@0.5 by **2.1**. Do you have any advice on my experiment?
> 
> <img alt="image" width="374" src="https://user-images.githubusercontent.com/32691813/227530100-b66a33cf-e7c0-4c9e-921c-7118dcaeb45f.png">

May be you can refer the training [log](https://drive.google.com/drive/folders/1mSmAxzHxEvXLd3IpxBsycdx9aigl7Wb3) we released? Our score is higher than yours. You can check the output config first.

**Comment by Haiyang-W** [comment]
Could you provide you training log? So that we can help you better.

**Comment by abc-def-g** [comment]
![image](https://user-images.githubusercontent.com/32691813/227750979-514ef73f-4d54-4b7f-8841-654c87e53e6c.png)

Recently, I ran another experiment to check the performance; the mAP@0.5 is only 47.8, still lower than the reported results in the paper.  The training logs are listed below.

[log_train_20230315-113630.txt](https://github.com/Haiyang-W/CAGroup3D/files/11070581/log_train_20230315-113630.txt)
[log_train_20230323-094706.txt](https://github.com/Haiyang-W/CAGroup3D/files/11070582/log_train_20230323-094706.txt)

**Comment by abc-def-g** [comment]
I checked your released log,  the map@0.5 is only 48.4, **also lower than the reported mAP@0.5 ( 50.2(49.5) ) by 1.1**.

**Comment by Haiyang-W** [comment]
> I checked your released log, the map@0.5 is only 48.4, **also lower than the reported mAP@0.5 ( 50.2(49.5) ) by 1.1**.

Yes, we reproduce the CAGroup3D by OpenPCDet, instead of the original MMDet3D. The sunrgbd model has a higher mAP@25 (67.1 vs 66.4) than the original paper, but lower performance in terms of mAP@0.5 (49.1 vs 49.5). The log we released is a map@0.25 higher version. You can try several times.  SUN RGB-D fluctuates significantly, training more times should yield better results than the pre-trained models we provide.

**Comment by Haiyang-W** [comment]
> I checked your released log, the map@0.5 is only 48.4, **also lower than the reported mAP@0.5 ( 50.2(49.5) ) by 1.1**.

Moreover,  SUN RGB-D is a little small, so there is overfitting. You can refer the training log we released. The best performance is always on first lr deacy, (i.e., epoch 10 and 11 with 49.0, 49.2 map@0.5).
