### ISSUE TITLE
Environment configuration problem

### ISSUE THREAD

**Issue by Daybreak-Zheng** [Haiyang-W/CAGroup3D#13]
Thank you very much for your excellent work。

We had some problems setting up the environment，Ask if these warnings will have any impact？How did these warnings come about？
![image](https://user-images.githubusercontent.com/44741080/229676366-721dac01-cd02-4c30-bd42-63156d5e8829.png)

My environment configuration is 3090， torch 1.10.0, cuda11.1, python 3.7.12

Sincerely hope for your reply!

**Comment by Haiyang-W** [comment]
PCDet occasionally encounters this problem, it does not necessarily affect performance. Therefore, you can try running it first. Notably, please try 2x8 or 4x4 (gpu_num, batchsize_per_gpu).

Best regards,
Haiyang

**Comment by Haiyang-W** [comment]
We also provide the training log and model weight, you can check your environment by them first.
