### ISSUE TITLE
How can I get the number of points for each point cloud in a batch?

### ISSUE THREAD

**Issue by Daybreak-Zheng** [Haiyang-W/CAGroup3D#14]
Thank you very much for your excellent work。
 How can I get the number of points for each point cloud in a batch?
The batch_dict contains the points of all the point clouds in a batch. What do I do if I want to get a point cloud in a batch?
Looking forward to your reply！

**Comment by Haiyang-W** [comment]
Please refer [this line](https://github.com/Haiyang-W/CAGroup3D/blob/b44f00519c3281a3dc22de2e38c4a154b4af5dc1/pcdet/models/detectors/cagroup3d.py#L20).  The first dim of points is batch id.
