### ISSUE TITLE
Question regarding bs_id

### ISSUE THREAD

**Issue by Laktus** [Haiyang-W/CAGroup3D#17]
Hey,

As part of a masters curriculum i'm trying to integrate CAGroup3D into RfDNet. One of our post docs, wrote RfDNet and wants us to replace the 3D-Detector in there with a newer/better one and i decided for CAGroup3D.
RfDNet is working with scannet and expecting points with atleast 3 in the length of dimension (x,y,z) and additional features.

In the CAGroup3D class i see following code:

```
def voxelization(self, points):
        """voxelize input points."""
        # points Nx7 (bs_id, x, y, z, r, g, b)
        coordinates = points[:, :4].clone()
        coordinates[:, 1:] /= self.voxel_size
        features = points[:, 4:].clone()
        sp_tensor = ME.SparseTensor(coordinates=coordinates, features=features)
        return sp_tensor
```

Which says that the points are here actually with an additonal `bs_id `at the beginning. What is this `bs_id` value? I tried to look through your [Scannet](https://github.com/Haiyang-W/CAGroup3D/blob/main/pcdet/datasets/scannet/scannet_dataset.py) class, but  the `prepare_data` just says that the points are returned in the form x,y,z and additional feature, no `bs_id`. Where does it come from? And what is the meaning of this value/What is the value used for?

**Comment by Haiyang-W** [comment]
> Hey,
> 
> As part of a masters curriculum i'm trying to integrate CAGroup3D into RfDNet. One of our post docs, wrote RfDNet and wants us to replace the 3D-Detector in there with a newer/better one and i decided for CAGroup3D. RfDNet is working with scannet and expecting points with atleast 3 in the length of dimension (x,y,z) and additional features.
> 
> In the CAGroup3D class i see following code:
> 
> ```
> def voxelization(self, points):
>         """voxelize input points."""
>         # points Nx7 (bs_id, x, y, z, r, g, b)
>         coordinates = points[:, :4].clone()
>         coordinates[:, 1:] /= self.voxel_size
>         features = points[:, 4:].clone()
>         sp_tensor = ME.SparseTensor(coordinates=coordinates, features=features)
>         return sp_tensor
> ```
> 
> Which says that the points are here actually with an additonal `bs_id `at the beginning. What is this `bs_id` value? I tried to look through your [Scannet](https://github.com/Haiyang-W/CAGroup3D/blob/main/pcdet/datasets/scannet/scannet_dataset.py) class, but the `prepare_data` just says that the points are returned in the form x,y,z and additional feature, no `bs_id`. Where does it come from? And what is the meaning of this value/What is the value used for?

Please see [here](https://github.com/Haiyang-W/CAGroup3D/blob/b44f00519c3281a3dc22de2e38c4a154b4af5dc1/pcdet/datasets/dataset.py#L174). It's generated in collate_batch function.

**Comment by Haiyang-W** [comment]
> Hey,
> 
> As part of a masters curriculum i'm trying to integrate CAGroup3D into RfDNet. One of our post docs, wrote RfDNet and wants us to replace the 3D-Detector in there with a newer/better one and i decided for CAGroup3D. RfDNet is working with scannet and expecting points with atleast 3 in the length of dimension (x,y,z) and additional features.
> 
> In the CAGroup3D class i see following code:
> 
> ```
> def voxelization(self, points):
>         """voxelize input points."""
>         # points Nx7 (bs_id, x, y, z, r, g, b)
>         coordinates = points[:, :4].clone()
>         coordinates[:, 1:] /= self.voxel_size
>         features = points[:, 4:].clone()
>         sp_tensor = ME.SparseTensor(coordinates=coordinates, features=features)
>         return sp_tensor
> ```
> 
> Which says that the points are here actually with an additonal `bs_id `at the beginning. What is this `bs_id` value? I tried to look through your [Scannet](https://github.com/Haiyang-W/CAGroup3D/blob/main/pcdet/datasets/scannet/scannet_dataset.py) class, but the `prepare_data` just says that the points are returned in the form x,y,z and additional feature, no `bs_id`. Where does it come from? And what is the meaning of this value/What is the value used for?

It means that this point belongs to which sample, used in sparse convolution.
