### ISSUE TITLE
How to visual the predicted results?

### ISSUE THREAD

**Issue by Pioneer12138** [Haiyang-W/CAGroup3D#21]
Hey! I encounter some problems. When I want to evaluate the model, I find the test.py can not output the predicted results into a file. In test.py the code "parser.add_argument('--save_to_file', action='store_true', default=False, help='')" seems to fail to work it out.

**Comment by Haiyang-W** [comment]
Sorry for the late reply. We only implement CAGroup3D based on PCDet, but the compatibility of visualization is not considered.
