### ISSUE TITLE
data preprocessing scripts

### ISSUE THREAD

**Issue by fangchuan** [Haiyang-W/CAGroup3D#25]
Hi, thanks for your awesome work!

I am going to follow your publication and want to transplant your code into my dataset, could you release the dataset preprocessing code?  It would be helpful that you can share those scripts.

Many thanks! @Haiyang-W

**Comment by Haiyang-W** [comment]
Our data preprocessing strictly follows the mmdetection3d (0.15) version. The inconsistency should only be in the coordinate system compared to the existing mmdetection3d.
