### ISSUE TITLE
在loss.backward()的反向传播过程中，出现了报错

### ISSUE THREAD

**Issue by ssdxc** [Haiyang-W/CAGroup3D#7]
在CAGroup3D/tools/train_utils/train_utils.py的第74行的loss.backward()语句，出现了merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered。我在网上搜索发现问题是由于MinkowskiEngine-0.5.4产生的。我才用的环境与你的相同，请问你在实验过程中遇到了这种问题么，怎么来解决呢？

**Comment by Haiyang-W** [comment]
谢谢您关注我们的工作，我在实验过程中未遇到这个问题，可能是机器环境与CUDA版本有关，或许您可以再尝试一下，应该只要能正常安装MinkowskiEngine应该就可以。我正在赶一些DDL，3月16号后如果您还没有搞定这个问题，或许我们可以一起来看一下。希望可以帮助到你。

祝好！
海洋

**Comment by ssdxc** [comment]
感谢你的及时回复，我在更换了1.12版本的torch后解决了这个问题。我使用的机器是CUDA11.2，更换了torch后在一些cpp的编译过程中会出一些错误，不过很好解决。在结果复现后我会给你关于我的环境是否能完全复现您的实验。祝你在DDL前完成你的工作！

**Comment by Haiyang-W** [comment]
好的，欢迎随时讨论。祝您一切顺利 :)
