### ISSUE TITLE
always zero orientation in pred_boxes

### ISSUE THREAD

**Issue by binbin-xu** [Haiyang-W/CAGroup3D#9]
Hi Haiyang,

Thank you very much for open source this great work! 
Since you did not release your pretrained weights on ScanNet yet, I tried to train it using your provided config. The mAP from my trained weight can get similar results in your paper, however, I found that the predicted orientation in the bounding box detection (the last element in pred_boxes) are all zero, on both ScanNet and my self-collected data. 
Can I ask if that also happens on your side or you have fixed this issue? Thanks!

**Comment by Haiyang-W** [comment]
> > Hi Haiyang,
> > Yes
> > Thank you very much for open source this great work! Since you did not release your pretrained weights on ScanNet yet, I tried to train it using your provided config. The mAP from my trained weight can get similar results in your paper, however, I found that the predicted orientation in the he last element in pred_boxes) are all zero, on both ScanNet and my self-collected data. Can I ask if that also happens on your side or you have fixed this issue? Thank
> 
> Yes, the bbox of scannet is axis-aligned. That means the direction of all bounding boxes are zero. You can check the Sun RGB-D. Its bboxes is orientated.
> 
> Hope that can solve your problems!
> 
> Best regards. Haiyang

Axis-aligned bbox is the standard data pre-processing of Scannet. We just follow the implementation of MMDet3D.

**Comment by binbin-xu** [comment]
I see. Thanks very much for resolving my questions!
